title: "Leiden-BuurtKennis"
description: "Public documentation of citizen science methods from Leiden Citizen Science Lab"

# Use the remote theme so GitHub Pages can find it
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://citizensciencelab.github.io/Leiden-BuurtKennis
search_enabled: true

just_the_docs:
color_scheme: brown
